title: Marc Deely Portfolio
email: themarcusdeely@gmail.com
description: "Portfolio site for Marc Deely."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:/marcdeely.com" # the base hostname & protocol for your site, e.g. http://example.com
hosturl: "https:/marcdeely.com"
instagram_username: marcusdeely 
github_username:  mdeely
image_path: "https://storage.googleapis.com/portfolio_images"
ogImage: "logo_1200.png"
ogImageAlt: "Marc Deely's Portfolio"

collections:
  projects:
    output: true
    permalink: "/projects/:slug"

sass:
  sass_dir: _sass
 
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
